language: python

python: "3.8"

git:
  depth: 1

branches:
  only:
    - main
    - ci-integration
    - /^iteration-\d$/

install:
  - pip install -r requirements.txt

script:
  - coverage run manage.py test

after_script:
  - bash <(curl -s https://codecov.io/bash)